name: Actualisation Flux RSS

on:
  schedule:
    - cron: '0 * * * *' # S'exécute toutes les heures
  workflow_dispatch: # Permet de le lancer manuellement

permissions:
  contents: write # CETTE LIGNE EST ESSENTIELLE POUR AUTORISER LE PUSH

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Mise à jour de la veille
        run: node update_veille.js

      - name: Sauvegarde des changements sur GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add veille_data.json
          git commit -m "Automatique: Mise à jour flux RSS" || echo "Pas de changements"
          git push